### ISSUE TITLE
The code of MFAN

### ISSUE THREAD

**Issue by Chenwangxing** [ME-SJTU/MFAN#1]
I came across your work on 'MFAN: Mixing Feature Attention Network for trajectory prediction' and I found it really fascinating! When will you release the code? I promise to cite your work in any applications, papers, or articles. Thank you!​

**Comment by ME-SJTU** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you for your interest and appreciation of our work. I will release the raw code in 3 days. Further details about the MFAN will be made available shortly thereafter.
        
    
        
            
        
    
    
        
        

        
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        6/8/2024 11:03
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [ME-SJTU/MFAN] The code of MFAN (Issue #1)
        
      
    
  
  
I came across your work on 'MFAN: Mixing Feature Attention Network for trajectory prediction' and I found it really fascinating! When will you release the code? I promise to cite your work in any applications, papers, or articles. Thank you!

**Comment by Chenwangxing** [comment]
Thank you so much!

**Comment by Chenwangxing** [comment]
Thanks for the code provided by the author. Could you provide the training and testing code? This part of the code will help me understand the full text better. 
Have a nice day!

**Comment by ME-SJTU** [comment]
Thanks for your interest and support. We have released our training and testing scripts to give you a more complete understanding of the implementation. We hope this additional material will be useful for your studies and projects.
